/* CRIANDO O BANCO DE DADOS PARA TESTES */
CREATE DATABASE TRIGGERS;

/* ENTRANDO NO BANCO DE DADOS */
USE TRIGGERS;

/* CRIANDO A TABELA DE TESTES */
CREATE TABLE USUARIOS(
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    LOGIN VARCHAR(30),
    SENHA VARCHAR(100)
);

/* CRIANDO UMA TABELA QUE RECEBERA O BACKUP DOS USUARIOS */
CREATE TABLE BKP_USUARIOS(
    IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
    IDUSUARIO INT,
    NOME VARCHAR(30),
    LOGIN VARCHAR(30)
);
