/* ALIMENTANDO AS TABELA */
INSERT INTO USUARIOS VALUES (NULL, 'FULANO', 'FULANO', 'FULANO123@');
INSERT INTO USUARIOS VALUES (NULL, 'BELTRANO', 'BELTRANO', 'BELTRANO123@');
INSERT INTO USUARIOS VALUES (NULL, 'CICLANO', 'CICLANO', 'CICLANO123@');
INSERT INTO USUARIOS VALUES (NULL, 'RODRIGO', 'RODRIGO', 'RODRIGO123@');
INSERT INTO USUARIOS VALUES (NULL, 'DIEGO', 'DIEGO', 'DIEGO123@');