/* MUDANDO O DELIMITADOR DE ; PARA $ PARA FAZER A TRIGGER */
DELIMITER $


/* CRIANDO UMA TRIGGER QUE FAZ BACKUP DO USUARIO DELETADO EM OUTRA TABELA (SEM SALVAR A SENHA POR SEGURANÇA) */ 
CREATE TRIGGER BACKUP_USUARIOS
BEFORE DELETE ON USUARIOS
FOR EACH ROW
BEGIN 

    INSERT INTO BKP_USUARIOS VALUES (NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);

END$

/* VOLTANDO O DELIMITADOR AO PADRÃO */
DELIMITER ;