/* QUERIES DE VERIFICAÇÃO */


/* TRAGA OS FUNCIONARIOS QUE TRABALHEM
   NO DEPARTAMENTO DE FILMES OU NO
   DEPARTAMENTO DE ROUPAS */
      
-- VERIFICANDO QUAL DEPARTAMENTO TEM MAIS CADASTROS PARA MELHORAR A PERFORMANCE DO SELECT
-- 21 FILMES
-- 53 ROUPAS	  
SELECT COUNT(*), DEPARTAMENTO
		FROM FUNCIONARIOS
	GROUP BY DEPARTAMENTO
    ORDER BY 1;
	
   
SELECT *
  FROM FUNCIONARIOS
 WHERE DEPARTAMENTO = 'ROUPAS'
    OR DEPARTAMENTO = 'FILMES';
    
   
   
/* O GESTOR DE MARKETING PEDIU A LISTA DAS FUNCIONARIAS QUE TRABALHEM NO DEPARTAMENTO
   DE FILMES OU NO DEPARTAMENTO LAR. ELE NECESSITA ENVIAR UM EMAIL PARA AS COLABORADORAS
   DESSES DOIS SETORES  */   

-- FAZENDO O COUNT PARA VERIFICAR QUAL DEPARTAMENTO TEM MAIS CADASTROS PARA MELHORAR A PERFORMANCE DO SELECT
-- 21 FILMES 
-- 52 LAR
SELECT COUNT(*), DEPARTAMENTO
        FROM FUNCIONARIOS
	GROUP BY DEPARTAMENTO
	ORDER BY 1;
   
SELECT NOME 
     , EMAIL 
	 , DEPARTAMENTO
	 , SEXO
  FROM FUNCIONARIOS
 WHERE(DEPARTAMENTO = 'LAR' AND SEXO = 'FEMININO')
    OR (DEPARTAMENTO = 'FILMES' AND SEXO = 'FEMININO');
   
   
/* COMO ESTAMOS TRABALHANDO COM AND, COLOCAMOS
   O DEPARTAMENTO PRIMEIRO, POIS ELE IRÁ CHECAR A
   SEGUNDA CONDIÇÃO UM NUMERO MENOR DE VEZES */    



/* TRAGA OS FUNCIONARIOS DO SEXO MASCULINO
   OU OS FUNCIONARIOS QUE TRABALHAM NO JARDIM */
SELECT NOME
     , SEXO
	 , DEPARTAMENTO
  FROM FUNCIONARIOS
 WHERE SEXO = 'MASCULINO'
	OR DEPARTAMENTO = 'JARDIM';