/* CRIAÇÃO DO BANCO*/
CREATE DATABASE LIVRARIA;


/* CONECTANDO NO BANCO LIVRARIA */
USE LIVRARIA;


/* CRIAÇÃO DA TABELA LIVROS*/ 
CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(30),
	SEXO_AUTOR CHAR(1),
	NUMERO_PAGINAS INT(11),
	NOME_EDITORA VARCHAR(30),
	VALOR_LIVRO FLOAT(4,2),
	ESTADO_EDITORA CHAR(2),
	ANO_PUBLICACAO INT(4)
);