/* QUERIES DE PESQUISA */

/* TRAZER TODOS OS DADOS */
SELECT * FROM LIVROS;

/* TRAZER O NOME DO LIVRO E NOME DA EDITORA */
SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

/* TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO */
SELECT NOME_LIVRO, ESTADO_EDITORA FROM LIVROS
WHERE SEXO_AUTOR = 'M';

/* TRAZER O NOME DO LIVRO E NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO */
SELECT NOME_LIVRO, NUMERO_PAGINAS FROM LIVROS
WHERE SEXO_AUTOR = 'F';

/* TRAZER OS VALORES DO LIVROS DAS EDITORAS DE SÃO PAULO */
SELECT VALOR_LIVRO FROM LIVROS
WHERE ESTADO_EDITORA = 'SP';

/* TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO */
SELECT NOME_AUTOR, SEXO_AUTOR FROM LIVROS
WHERE SEXO_AUTOR = 'M' 
AND (ESTADO_EDITORA = 'SP' OR ESTADO_EDITORA = 'RJ'); 