-- CRIACAO DA DATABASE E DAS TABELAS PARA O EXERCICIO 03
CREATE DATABASE COMERCIO;

USE COMERCIO;

-- CRIANDO TABELAS DO BANCO COMERCIO
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE,
	EMAIL VARCHAR(100)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL UNIQUE,
	RUA VARCHAR(100),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO CHAR(2),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL,
	TIPO CHAR(3), -- COM, FIX, CEL
	NUMERO VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);