-- QUERIES DO EXERCICIO 03

-- RELATORIO GERAL DE TODOS OS CLIENTES
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;


-- RELATORIO DE HOMENS
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE C.SEXO = 'M';


-- RELATORIO DE MULHERES
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE C.SEXO = 'F'; 


-- QUANTIDADE DE HOMENS E MULHERES
SELECT SEXO, COUNT(*)
  FROM CLIENTE 
 GROUP BY SEXO;


-- IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NAO TENHAM CELULAR
SELECT C.IDCLIENTE, C.NOME, C.EMAIL, E.BAIRRO, E.CIDADE, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE E.BAIRRO LIKE '%CENTRO%'
   AND E.CIDADE = 'RIO DE JANEIRO'
   AND T.NUMERO = NULL;


-- MUDANDO OS CADASTROS COM O SEXO CADASTRADO ERRADO
UPDATE CLIENTE SET SEXO = 'F'
 WHERE IDCLIENTE IN (9, 10, 11, 15);


UPDATE CLIENTE SET SEXO = 'M'
 WHERE IDCLIENTE = '13'; 



/* PARA UM CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL, E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE T.TIPO = 'CEL'
   AND E.ESTADO = 'RJ'; 


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU 
UM RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR  
DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR*/

SELECT C.NOME, C.EMAIL, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE C.SEXO = 'F'
   AND T.TIPO = 'CEL'
   AND E.ESTADO = 'SP';