/* ALIMENTANDO A TABELA PRODUTO */
INSERT INTO PRODUTO VALUES (NULL, 'LAPISEIRA', 4.5);
INSERT INTO PRODUTO VALUES (NULL, 'PACOTE DE FOLHA A4', 15.5);
INSERT INTO PRODUTO VALUES (NULL, 'LAPIS', 1.50);
INSERT INTO PRODUTO VALUES (NULL, 'BORRACHA', 2.0);
INSERT INTO PRODUTO VALUES (NULL, 'CADERNO', 14.75);