/* SELECT NA TABELA PRODUTO */
SELECT * FROM PRODUTO;

/* SELECT NA TABELA BKP_PRODUTO NO BANCO DE DADOS BACKUP */
SELECT * FROM BACKUP.BKP_PRODUTO;

/* UPDATE NA TABELA PRODUTO (FAÇA APÓS CRIAR A TRIGGER) */
UPDATE PRODUTO SET VALOR = 17 WHERE IDPRODUTO = 5;