/* MUDANDO O DELIMITADOR */
DELIMITER $

/* CRIANDO UMA TRIGGER QUE FAZ UM BACKUP TODA VEZ QUE UM PRODUTO FOR ALTERADO NA TABELA PRODUTO NO BANCO DE DADOS LOJA */
CREATE TRIGGER AUDIT_PRODUTO
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN

    INSERT INTO BACKUP.BKP_PRODUTO VALUES (NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, NEW.VALOR, NOW(), CURRENT_USER(), 'U');

END$

/* VOLTANDO O DELIMITADOR PARA O PADRÃO */
DELIMITER ;