/* CRIANDO O BANCO PADRÃO */
CREATE DATABASE LOJA;

/* ENTRANDO NO BANCO PADRÃO */
USE LOJA;

/* CRIANDO A TABELA QUE SERÁ USADA PARA TESTES */
CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    VALOR FLOAT(10,2)
);


/* CRIANDO O BANCO DE DADOS DE BACKUP */
CREATE DATABASE BACKUP;

/* ENTRANDO NO BANCO DE DADOS BACKUP */
USE BACKUP;

/* CRIANDO A TABELA QUE FARA BACKUP DOS PRODUTOS */
CREATE TABLE BKP_PRODUTO(
    IDBKP INT PRIMARY KEY AUTO_INCREMENT,
    IDPRODUTO INT,
    NOME VARCHAR(255),
    VALOR FLOAT(10,2)
);