/* MUDANDO DELIMITADOR */
DELIMITER $

/* CRIANDO TRIGGER PARA SALVAR OS PRODUTOS SALVOS NA TABELA BKP_PRODUTO NO BANCO BACKUP */ 
CREATE TRIGGER BACKUP_PRODUTO
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN

    INSERT INTO BACKUP.BKP_PRODUTO VALUES (NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);

END$

/* VOLTANDO O DELIMITADOR AO PADRÃO */
DELIMITER ;